# Create and Fill Bank Monitoring Database

This notebook renders the bank monitoring DDL with Russian comments, creates the SQLite database through the project pipeline, and previews the first rows from each generated table.

In [4]:
from contextlib import redirect_stdout
import io
import os
from pathlib import Path
import sqlite3
import sys
from IPython.display import Markdown, display
import pandas as pd

from src.config import PROJECT_ROOT, RAW_DATA_DIR
from src.dataset import (  # noqa: E402
    build_database,
    render_ddl,
)


COMMENT_STYLE = "yaml" # "inline" or "yaml"
COMMENT_VARIANT = "business" # "short" or "business" or "technical"
PREVIEW_ROWS = 5
DATABASE_NAME = "sakila" # "bank_transaction_monitoring" or "sakila"
SCHEMA_MAPPING_PATH = os.path.join(RAW_DATA_DIR, DATABASE_NAME, "schema_mapping.json")

In [5]:
ddl = render_ddl(
    comment_style=COMMENT_STYLE,
    comment_variant=COMMENT_VARIANT,
    database_name=DATABASE_NAME 
)

print(ddl)

-- table: act
-- source_table: actor
-- description: Справочник актёров, участвующих в фильмах. Одна запись — один актёр с уникальным идентификатором, именем и фамилией.
-- columns:
--   a01: Уникальный идентификатор актёра. Используется для связи с фильмами через таблицу film_actor.  # source: actor_id
--   a02: Имя актёра. Используется в отчётах по фильмам и подборках актёрского состава.  # source: first_name
--   a03: Фамилия актёра. Необходима для поиска и сортировки в каталоге актёров.  # source: last_name
--   a04: Дата и время последнего изменения записи об актёре. Заполняется автоматически триггером.  # source: last_update

CREATE TABLE act (
  a01 numeric NOT NULL,
  a02 VARCHAR(45) NOT NULL,
  a03 VARCHAR(45) NOT NULL,
  a04 TIMESTAMP NOT NULL,
  PRIMARY KEY (a01)
);

CREATE INDEX idx_act_a03 ON act(a03);

CREATE TRIGGER act_trigger_ai AFTER INSERT ON act
BEGIN
  UPDATE act SET a04 = DATETIME('NOW') WHERE rowid = new.rowid;
END;

CREATE TRIGGER act_trigger_au AFTER UPDATE ON act
BEGIN
  UPDATE act SET a04 = DATETIME('NOW') WHERE rowid = new.rowid;
END;

-- table: cnt
-- source_table: country
-- description: Справочник стран, в которых находятся города и адреса клиентов, магазинов и сотрудников.
-- columns:
--   c01: Уникальный идентификатор страны. Используется для связи с таблицей city.  # source: country_id
--   c02: Название страны. Применяется в географических отчётах и адресных формах.  # source: country
--   c03: Дата и время последнего изменения записи о стране. Управляется триггерами.  # source: last_update

CREATE TABLE cnt (
  c01 SMALLINT NOT NULL,
  c02 VARCHAR(50) NOT NULL,
  c03 TIMESTAMP,
  PRIMARY KEY (c01)
);

CREATE TRIGGER cnt_trigger_ai AFTER INSERT ON cnt
BEGIN
  UPDATE cnt SET c03 = DATETIME('NOW') WHERE rowid = new.rowid;
END;

CREATE TRIGGER cnt_trigger_au AFTER UPDATE ON cnt
BEGIN
  UPDATE cnt SET c03 = DATETIME('NOW') WHERE rowid = new.rowid;
END;

-- table: cty
-- source_table: city
-- description: Справочник городов, привязанных к странам. Используется для построения адресов.
-- columns:
--   d01: Уникальный идентификатор города. Связывается с таблицей address.  # source: city_id
--   d02: Название города. Влияет на региональную аналитику продаж.  # source: city
--   d03: Идентификатор страны, к которой относится город. Внешний ключ к cnt.  # source: country_id
--   d04: Время последнего обновления записи о городе. Заполняется автоматически.  # source: last_update

CREATE TABLE cty (
  d01 int NOT NULL,
  d02 VARCHAR(50) NOT NULL,
  d03 SMALLINT NOT NULL,
  d04 TIMESTAMP NOT NULL,
  PRIMARY KEY (d01),
  CONSTRAINT fk_cty_cnt FOREIGN KEY (d03) REFERENCES cnt (c01) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE INDEX idx_fk_d03 ON cty(d03);

CREATE TRIGGER cty_trigger_ai AFTER INSERT ON cty
BEGIN
  UPDATE cty SET d04 = DATETIME('NOW') WHERE rowid = new.rowid;
END;

CREATE TRIGGER cty_trigger_au AFTER UPDATE ON cty
BEGIN
  UPDATE cty SET d04 = DATETIME('NOW') WHERE rowid = new.rowid;
END;

-- table: adr
-- source_table: address
-- description: Таблица адресов клиентов, магазинов и сотрудников. Включает улицу, район, телефон и почтовый индекс.
-- columns:
--   e01: Уникальный идентификатор адреса. Ссылается из таблиц customer, staff, store.  # source: address_id
--   e02: Основная строка адреса (улица, дом). Используется в доставке и коммуникациях.  # source: address
--   e03: Дополнительная строка адреса (корпус, строение). Может быть пустой.  # source: address2
--   e04: Район или округ. Полезен для региональной аналитики.  # source: district
--   e05: Идентификатор города. Внешний ключ к cty.  # source: city_id
--   e06: Почтовый индекс. Используется в отчётах и для сверки адресов.  # source: postal_code
--   e07: Контактный телефон. Необходим для связи с клиентами и сотрудниками.  # source: phone
--   e08: Дата последнего изменения адреса. Устанавливается триггерами.  # source: last_update

CREATE TABLE adr (
  e01 int NOT NULL,
  e02 VARCHAR(50) NOT NULL,
  e03 VARCHAR(50) DEFAULT NULL,
  e04 VARCHAR(20) NOT NULL,
  e05 INT NOT NULL,
  e06 VARCHAR(10) DEFAULT NULL,
  e07 VARCHAR(20) NOT NULL,
  e08 TIMESTAMP NOT NULL,
  PRIMARY KEY (e01),
  CONSTRAINT fk_adr_cty FOREIGN KEY (e05) REFERENCES cty (d01) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE INDEX idx_fk_e05 ON adr(e05);

CREATE TRIGGER adr_trigger_ai AFTER INSERT ON adr
BEGIN
  UPDATE adr SET e08 = DATETIME('NOW') WHERE rowid = new.rowid;
END;

CREATE TRIGGER adr_trigger_au AFTER UPDATE ON adr
BEGIN
  UPDATE adr SET e08 = DATETIME('NOW') WHERE rowid = new.rowid;
END;

-- table: lng
-- source_table: language
-- description: Справочник языков, на которых представлены фильмы (например, английский, французский).
-- columns:
--   f01: Уникальный идентификатор языка. Связывается с фильмами в таблице film.  # source: language_id
--   f02: Название языка (до 20 символов). Используется в фильтрации каталога.  # source: name
--   f03: Дата и время последнего обновления записи о языке. Управляется триггерами.  # source: last_update

CREATE TABLE lng (
  f01 SMALLINT NOT NULL,
  f02 CHAR(20) NOT NULL,
  f03 TIMESTAMP NOT NULL,
  PRIMARY KEY (f01)
);

CREATE TRIGGER lng_trigger_ai AFTER INSERT ON lng
BEGIN
  UPDATE lng SET f03 = DATETIME('NOW') WHERE rowid = new.rowid;
END;

CREATE TRIGGER lng_trigger_au AFTER UPDATE ON lng
BEGIN
  UPDATE lng SET f03 = DATETIME('NOW') WHERE rowid = new.rowid;
END;

-- table: cat
-- source_table: category
-- description: Справочник категорий фильмов (например, комедия, ужасы, драма).
-- columns:
--   g01: Уникальный идентификатор категории. Используется в film_category.  # source: category_id
--   g02: Название категории. Применяется в аналитике продаж по жанрам.  # source: name
--   g03: Дата последнего изменения категории. Заполняется автоматически.  # source: last_update

CREATE TABLE cat (
  g01 SMALLINT NOT NULL,
  g02 VARCHAR(25) NOT NULL,
  g03 TIMESTAMP NOT NULL,
  PRIMARY KEY (g01)
);

CREATE TRIGGER cat_trigger_ai AFTER INSERT ON cat
BEGIN
  UPDATE cat SET g03 = DATETIME('NOW') WHERE rowid = new.rowid;
END;

CREATE TRIGGER cat_trigger_au AFTER UPDATE ON cat
BEGIN
  UPDATE cat SET g03 = DATETIME('NOW') WHERE rowid = new.rowid;
END;

-- table: cus
-- source_table: customer
-- description: Таблица клиентов проката. Содержит персональные данные, адрес, статус активности.
-- columns:
--   h01: Уникальный идентификатор клиента. Основной ключ для связей с rental и payment.  # source: customer_id
--   h02: Идентификатор магазина, к которому привязан клиент. Внешний ключ к store.  # source: store_id
--   h03: Имя клиента. Используется в отчётах и уведомлениях.  # source: first_name
--   h04: Фамилия клиента. Участвует в поиске и сортировке.  # source: last_name
--   h05: Электронная почта клиента. Используется для коммуникаций.  # source: email
--   h06: Идентификатор адреса клиента. Внешний ключ к address.  # source: address_id
--   h07: Статус активности клиента: 'Y' — активен, 'N' — неактивен.  # source: active
--   h08: Дата регистрации клиента. Влияет на историю и лояльность.  # source: create_date
--   h09: Дата последнего обновления записи клиента. Устанавливается триггерами.  # source: last_update

CREATE TABLE cus (
  h01 INT NOT NULL,
  h02 INT NOT NULL,
  h03 VARCHAR(45) NOT NULL,
  h04 VARCHAR(45) NOT NULL,
  h05 VARCHAR(50) DEFAULT NULL,
  h06 INT NOT NULL,
  h07 CHAR(1) DEFAULT 'Y' NOT NULL,
  h08 TIMESTAMP NOT NULL,
  h09 TIMESTAMP NOT NULL,
  PRIMARY KEY (h01),
  CONSTRAINT fk_cus_sto FOREIGN KEY (h02) REFERENCES sto (j01) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT fk_cus_adr FOREIGN KEY (h06) REFERENCES adr (e01) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE INDEX idx_cus_fk_h02 ON cus(h02);
CREATE INDEX idx_cus_fk_h06 ON cus(h06);
CREATE INDEX idx_cus_h04 ON cus(h04);

CREATE TRIGGER cus_trigger_ai AFTER INSERT ON cus
BEGIN
  UPDATE cus SET h09 = DATETIME('NOW') WHERE rowid = new.rowid;
END;

CREATE TRIGGER cus_trigger_au AFTER UPDATE ON cus
BEGIN
  UPDATE cus SET h09 = DATETIME('NOW') WHERE rowid = new.rowid;
END;

-- table: flm
-- source_table: film
-- description: Таблица фильмов. Содержит название, описание, язык, продолжительность, рейтинг и особенности.
-- columns:
--   i01: Уникальный идентификатор фильма. Связывается с inventory, film_actor, film_category.  # source: film_id
--   i02: Название фильма. Основное поле для поиска в каталоге.  # source: title
--   i03: Описание фильма (текст, может быть длинным).  # source: description
--   i04: Год выпуска фильма (4 символа).  # source: release_year
--   i05: Идентификатор языка фильма. Внешний ключ к language.  # source: language_id
--   i06: Идентификатор оригинального языка (если это дубляж или субтитры). Может быть NULL.  # source: original_language_id
--   i07: Длительность аренды в днях (по умолчанию 3).  # source: rental_duration
--   i08: Стоимость аренды за период (по умолчанию 4.99).  # source: rental_rate
--   i09: Длительность фильма в минутах.  # source: length
--   i10: Стоимость замены при утере (по умолчанию 19.99).  # source: replacement_cost
--   i11: Рейтинг MPAA: G, PG, PG-13, R, NC-17.  # source: rating
--   i12: Особенности фильма: Trailers, Commentaries, Deleted Scenes, Behind the Scenes.  # source: special_features
--   i13: Дата последнего обновления фильма. Устанавливается триггерами.  # source: last_update

CREATE TABLE flm (
  i01 int NOT NULL,
  i02 VARCHAR(255) NOT NULL,
  i03 BLOB SUB_TYPE TEXT DEFAULT NULL,
  i04 VARCHAR(4) DEFAULT NULL,
  i05 SMALLINT NOT NULL,
  i06 SMALLINT DEFAULT NULL,
  i07 SMALLINT DEFAULT 3 NOT NULL,
  i08 DECIMAL(4,2) DEFAULT 4.99 NOT NULL,
  i09 SMALLINT DEFAULT NULL,
  i10 DECIMAL(5,2) DEFAULT 19.99 NOT NULL,
  i11 VARCHAR(10) DEFAULT 'G',
  i12 VARCHAR(100) DEFAULT NULL,
  i13 TIMESTAMP NOT NULL,
  PRIMARY KEY (i01),
  CONSTRAINT CHECK_flm_i12 CHECK(i12 is null OR i12 LIKE '%Trailers%' OR i12 LIKE '%Commentaries%' OR i12 LIKE '%Deleted Scenes%' OR i12 LIKE '%Behind the Scenes%'),
  CONSTRAINT CHECK_flm_i11 CHECK(i11 IN ('G','PG','PG-13','R','NC-17')),
  CONSTRAINT fk_flm_lng FOREIGN KEY (i05) REFERENCES lng (f01),
  CONSTRAINT fk_flm_lng_original FOREIGN KEY (i06) REFERENCES lng (f01)
);

CREATE INDEX idx_fk_i05 ON flm(i05);
CREATE INDEX idx_fk_i06 ON flm(i06);

CREATE TRIGGER flm_trigger_ai AFTER INSERT ON flm
BEGIN
  UPDATE flm SET i13 = DATETIME('NOW') WHERE rowid = new.rowid;
END;

CREATE TRIGGER flm_trigger_au AFTER UPDATE ON flm
BEGIN
  UPDATE flm SET i13 = DATETIME('NOW') WHERE rowid = new.rowid;
END;

-- table: fla
-- source_table: film_actor
-- description: Связующая таблица между актёрами и фильмами (many-to-many).
-- columns:
--   k01: Идентификатор актёра. Внешний ключ к actor.  # source: actor_id
--   k02: Идентификатор фильма. Внешний ключ к film.  # source: film_id
--   k03: Дата последнего обновления связи. Триггерная.  # source: last_update

CREATE TABLE fla (
  k01 INT NOT NULL,
  k02 INT NOT NULL,
  k03 TIMESTAMP NOT NULL,
  PRIMARY KEY (k01, k02),
  CONSTRAINT fk_fla_act FOREIGN KEY (k01) REFERENCES act (a01) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT fk_fla_flm FOREIGN KEY (k02) REFERENCES flm (i01) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE INDEX idx_fk_fla_k02 ON fla(k02);
CREATE INDEX idx_fk_fla_k01 ON fla(k01);

CREATE TRIGGER fla_trigger_ai AFTER INSERT ON fla
BEGIN
  UPDATE fla SET k03 = DATETIME('NOW') WHERE rowid = new.rowid;
END;

CREATE TRIGGER fla_trigger_au AFTER UPDATE ON fla
BEGIN
  UPDATE fla SET k03 = DATETIME('NOW') WHERE rowid = new.rowid;
END;

-- table: flc
-- source_table: film_category
-- description: Связующая таблица между фильмами и категориями (many-to-many).
-- columns:
--   l01: Идентификатор фильма. Внешний ключ к film.  # source: film_id
--   l02: Идентификатор категории. Внешний ключ к category.  # source: category_id
--   l03: Дата последнего обновления связи.  # source: last_update

CREATE TABLE flc (
  l01 INT NOT NULL,
  l02 SMALLINT NOT NULL,
  l03 TIMESTAMP NOT NULL,
  PRIMARY KEY (l01, l02),
  CONSTRAINT fk_flc_flm FOREIGN KEY (l01) REFERENCES flm (i01) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT fk_flc_cat FOREIGN KEY (l02) REFERENCES cat (g01) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE INDEX idx_fk_flc_l01 ON flc(l01);
CREATE INDEX idx_fk_flc_l02 ON flc(l02);

CREATE TRIGGER flc_trigger_ai AFTER INSERT ON flc
BEGIN
  UPDATE flc SET l03 = DATETIME('NOW') WHERE rowid = new.rowid;
END;

CREATE TRIGGER flc_trigger_au AFTER UPDATE ON flc
BEGIN
  UPDATE flc SET l03 = DATETIME('NOW') WHERE rowid = new.rowid;
END;

-- table: flt
-- source_table: film_text
-- description: Текстовая таблица для полнотекстового поиска по фильмам (film_text).
-- columns:
--   m01: Идентификатор фильма (связь с film).  # source: film_id
--   m02: Название фильма для поисковых запросов.  # source: title
--   m03: Описание фильма для полнотекстового индекса.  # source: description

CREATE TABLE flt (
  m01 SMALLINT NOT NULL,
  m02 VARCHAR(255) NOT NULL,
  m03 BLOB SUB_TYPE TEXT,
  PRIMARY KEY (m01)
);

-- table: inv
-- source_table: inventory
-- description: Таблица инвентаря — копий фильмов, доступных в магазинах.
-- columns:
--   n01: Уникальный идентификатор копии фильма (инвентарный номер).  # source: inventory_id
--   n02: Идентификатор фильма. Внешний ключ к film.  # source: film_id
--   n03: Идентификатор магазина, где находится копия. Внешний ключ к store.  # source: store_id
--   n04: Дата последнего обновления инвентаря. Триггерная.  # source: last_update

CREATE TABLE inv (
  n01 INT NOT NULL,
  n02 INT NOT NULL,
  n03 INT NOT NULL,
  n04 TIMESTAMP NOT NULL,
  PRIMARY KEY (n01),
  CONSTRAINT fk_inv_sto FOREIGN KEY (n03) REFERENCES sto (j01) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT fk_inv_flm FOREIGN KEY (n02) REFERENCES flm (i01) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE INDEX idx_fk_n02 ON inv(n02);
CREATE INDEX idx_fk_n03_n02 ON inv(n03, n02);

CREATE TRIGGER inv_trigger_ai AFTER INSERT ON inv
BEGIN
  UPDATE inv SET n04 = DATETIME('NOW') WHERE rowid = new.rowid;
END;

CREATE TRIGGER inv_trigger_au AFTER UPDATE ON inv
BEGIN
  UPDATE inv SET n04 = DATETIME('NOW') WHERE rowid = new.rowid;
END;

-- table: stf
-- source_table: staff
-- description: Таблица сотрудников проката. Содержит личные данные, фото, учётные данные и активность.
-- columns:
--   o01: Уникальный идентификатор сотрудника. Ссылается из rental, payment, store.  # source: staff_id
--   o02: Имя сотрудника.  # source: first_name
--   o03: Фамилия сотрудника.  # source: last_name
--   o04: Идентификатор адреса сотрудника. Внешний ключ к address.  # source: address_id
--   o05: Фотография сотрудника (BLOB, может быть NULL).  # source: picture
--   o06: Электронная почта сотрудника.  # source: email
--   o07: Идентификатор магазина, в котором работает сотрудник.  # source: store_id
--   o08: Статус активности (1 — активен, 0 — неактивен).  # source: active
--   o09: Логин сотрудника в системе.  # source: username
--   o10: Пароль (хэшированный или открытый, до 40 символов).  # source: password
--   o11: Дата последнего обновления записи сотрудника.  # source: last_update

CREATE TABLE stf (
  o01 SMALLINT NOT NULL,
  o02 VARCHAR(45) NOT NULL,
  o03 VARCHAR(45) NOT NULL,
  o04 INT NOT NULL,
  o05 BLOB DEFAULT NULL,
  o06 VARCHAR(50) DEFAULT NULL,
  o07 INT NOT NULL,
  o08 SMALLINT DEFAULT 1 NOT NULL,
  o09 VARCHAR(16) NOT NULL,
  o10 VARCHAR(40) DEFAULT NULL,
  o11 TIMESTAMP NOT NULL,
  PRIMARY KEY (o01),
  CONSTRAINT fk_stf_sto FOREIGN KEY (o07) REFERENCES sto (j01) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT fk_stf_adr FOREIGN KEY (o04) REFERENCES adr (e01) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE INDEX idx_fk_stf_o07 ON stf(o07);
CREATE INDEX idx_fk_stf_o04 ON stf(o04);

CREATE TRIGGER stf_trigger_ai AFTER INSERT ON stf
BEGIN
  UPDATE stf SET o11 = DATETIME('NOW') WHERE rowid = new.rowid;
END;

CREATE TRIGGER stf_trigger_au AFTER UPDATE ON stf
BEGIN
  UPDATE stf SET o11 = DATETIME('NOW') WHERE rowid = new.rowid;
END;

-- table: sto
-- source_table: store
-- description: Таблица магазинов проката. У каждого есть менеджер и адрес.
-- columns:
--   j01: Уникальный идентификатор магазина. Связывается с inventory, customer, staff.  # source: store_id
--   j02: Идентификатор сотрудника — менеджера магазина. Внешний ключ к staff.  # source: manager_staff_id
--   j03: Идентификатор адреса магазина. Внешний ключ к address.  # source: address_id
--   j04: Дата последнего обновления магазина.  # source: last_update

CREATE TABLE sto (
  j01 INT NOT NULL,
  j02 SMALLINT NOT NULL,
  j03 INT NOT NULL,
  j04 TIMESTAMP NOT NULL,
  PRIMARY KEY (j01),
  CONSTRAINT fk_sto_stf FOREIGN KEY (j02) REFERENCES stf (o01),
  CONSTRAINT fk_sto_adr FOREIGN KEY (j03) REFERENCES adr (e01)
);

CREATE INDEX idx_sto_fk_j02 ON sto(j02);
CREATE INDEX idx_fk_sto_j03 ON sto(j03);

CREATE TRIGGER sto_trigger_ai AFTER INSERT ON sto
BEGIN
  UPDATE sto SET j04 = DATETIME('NOW') WHERE rowid = new.rowid;
END;

CREATE TRIGGER sto_trigger_au AFTER UPDATE ON sto
BEGIN
  UPDATE sto SET j04 = DATETIME('NOW') WHERE rowid = new.rowid;
END;

-- table: pay
-- source_table: payment
-- description: Таблица платежей клиентов за аренду. Содержит сумму, дату и связи с rental, customer, staff.
-- columns:
--   p01: Уникальный идентификатор платежа.  # source: payment_id
--   p02: Идентификатор клиента, совершившего платёж. Внешний ключ к customer.  # source: customer_id
--   p03: Идентификатор сотрудника, принявшего платёж. Внешний ключ к staff.  # source: staff_id
--   p04: Идентификатор аренды, за которую произведён платёж. Может быть NULL.  # source: rental_id
--   p05: Сумма платежа (до 2 знаков после запятой).  # source: amount
--   p06: Дата и время платежа.  # source: payment_date
--   p07: Дата последнего обновления записи платежа. Триггерная.  # source: last_update

CREATE TABLE pay (
  p01 int NOT NULL,
  p02 INT NOT NULL,
  p03 SMALLINT NOT NULL,
  p04 INT DEFAULT NULL,
  p05 DECIMAL(5,2) NOT NULL,
  p06 TIMESTAMP NOT NULL,
  p07 TIMESTAMP NOT NULL,
  PRIMARY KEY (p01),
  CONSTRAINT fk_pay_ren FOREIGN KEY (p04) REFERENCES ren (q01) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_pay_cus FOREIGN KEY (p02) REFERENCES cus (h01),
  CONSTRAINT fk_pay_stf FOREIGN KEY (p03) REFERENCES stf (o01)
);

CREATE INDEX idx_fk_p03 ON pay(p03);
CREATE INDEX idx_fk_p02 ON pay(p02);

CREATE TRIGGER pay_trigger_ai AFTER INSERT ON pay
BEGIN
  UPDATE pay SET p07 = DATETIME('NOW') WHERE rowid = new.rowid;
END;

CREATE TRIGGER pay_trigger_au AFTER UPDATE ON pay
BEGIN
  UPDATE pay SET p07 = DATETIME('NOW') WHERE rowid = new.rowid;
END;

-- table: ren
-- source_table: rental
-- description: Таблица аренды фильмов. Фиксирует дату выдачи, возврата и связь с инвентарём, клиентом, сотрудником.
-- columns:
--   q01: Уникальный идентификатор аренды.  # source: rental_id
--   q02: Дата и время выдачи фильма.  # source: rental_date
--   q03: Идентификатор инвентарной копии. Внешний ключ к inventory.  # source: inventory_id
--   q04: Идентификатор клиента. Внешний ключ к customer.  # source: customer_id
--   q05: Дата возврата фильма (может быть NULL, если ещё не вернули).  # source: return_date
--   q06: Идентификатор сотрудника, оформившего аренду. Внешний ключ к staff.  # source: staff_id
--   q07: Дата последнего обновления аренды. Триггерная.  # source: last_update

CREATE TABLE ren (
  q01 INT NOT NULL,
  q02 TIMESTAMP NOT NULL,
  q03 INT NOT NULL,
  q04 INT NOT NULL,
  q05 TIMESTAMP DEFAULT NULL,
  q06 SMALLINT NOT NULL,
  q07 TIMESTAMP NOT NULL,
  PRIMARY KEY (q01),
  CONSTRAINT fk_ren_stf FOREIGN KEY (q06) REFERENCES stf (o01),
  CONSTRAINT fk_ren_inv FOREIGN KEY (q03) REFERENCES inv (n01),
  CONSTRAINT fk_ren_cus FOREIGN KEY (q04) REFERENCES cus (h01)
);

CREATE INDEX idx_ren_fk_q03 ON ren(q03);
CREATE INDEX idx_ren_fk_q04 ON ren(q04);
CREATE INDEX idx_ren_fk_q06 ON ren(q06);
CREATE UNIQUE INDEX idx_ren_uq ON ren (q02, q03, q04);

CREATE TRIGGER ren_trigger_ai AFTER INSERT ON ren
BEGIN
  UPDATE ren SET q07 = DATETIME('NOW') WHERE rowid = new.rowid;

In [6]:
db_path = build_database(
    comment_style=COMMENT_STYLE,
    comment_variant=COMMENT_VARIANT,
    database_name=DATABASE_NAME,
    overwrite=True,
)

print(f"SQLite database created: {db_path}")

schema_mapping = pd.read_json(SCHEMA_MAPPING_PATH, orient="index")
table_names = schema_mapping.index.tolist()

with sqlite3.connect(db_path) as connection:
    for table_name in table_names:
        row_count = connection.execute(f"SELECT COUNT(*) FROM {table_name}").fetchone()[0]
        display(Markdown(f"## `{table_name}` ({row_count} rows)"))
        display(pd.read_sql_query(f"SELECT * FROM {table_name} LIMIT {PREVIEW_ROWS}", connection))

SQLite database created: /home/user/cursor_projects/vanna-sql/data/processed/sakila/sakila_yaml_business.sqlite.db

## `act` (200 rows)

   a01       a02           a03                  a04
0    1  PENELOPE       GUINESS  2026-06-04 20:56:50
1    2      NICK      WAHLBERG  2026-06-04 20:56:50
2    3        ED         CHASE  2026-06-04 20:56:50
3    4  JENNIFER         DAVIS  2026-06-04 20:56:50
4    5    JOHNNY  LOLLOBRIGIDA  2026-06-04 20:56:50

## `cnt` (109 rows)

   c01             c02                  c03
0    1     Afghanistan  2026-06-04 20:56:50
1    2         Algeria  2026-06-04 20:56:50
2    3  American Samoa  2026-06-04 20:56:50
3    4          Angola  2026-06-04 20:56:50
4    5        Anguilla  2026-06-04 20:56:50

## `cty` (600 rows)

   d01                 d02  d03                  d04
0    1  A Corua (La Corua)   87  2026-06-04 20:56:50
1    2                Abha   82  2026-06-04 20:56:50
2    3           Abu Dhabi  101  2026-06-04 20:56:50
3    4                Acua   60  2026-06-04 20:56:50
4    5               Adana   97  2026-06-04 20:56:50

## `adr` (603 rows)

   e01                   e02   e03 e04  e05    e06 e07                  e08
0    1     47 MySakila Drive  None      300   None      2026-06-04 20:56:50
1    2    28 MySQL Boulevard  None      576   None      2026-06-04 20:56:50
2    3     23 Workhaven Lane  None      300   None      2026-06-04 20:56:50
3    4  1411 Lillydale Drive  None      576   None      2026-06-04 20:56:50
4    5        1913 Hanoi Way  None      463  35200      2026-06-04 20:56:50

## `lng` (6 rows)

   f01       f02                  f03
0    1   English  2026-06-04 20:56:50
1    2   Italian  2026-06-04 20:56:50
2    3  Japanese  2026-06-04 20:56:50
3    4  Mandarin  2026-06-04 20:56:50
4    5    French  2026-06-04 20:56:50

## `cat` (16 rows)

   g01        g02                  g03
0    1     Action  2026-06-04 20:56:50
1    2  Animation  2026-06-04 20:56:50
2    3   Children  2026-06-04 20:56:50
3    4   Classics  2026-06-04 20:56:50
4    5     Comedy  2026-06-04 20:56:50

## `cus` (599 rows)

,h01,h02,h03,h04,h05,h06,h07,h08,h09
0,1,1,MARY,SMITH,MARY.SMITH@sakilacustomer.org,5,1,2006-02-14 22:04:36.000,2026-06-04 20:56:50
1,2,1,PATRICIA,JOHNSON,PATRICIA.JOHNSON@sakilacustomer.org,6,1,2006-02-14 22:04:36.000,2026-06-04 20:56:50
2,3,1,LINDA,WILLIAMS,LINDA.WILLIAMS@sakilacustomer.org,7,1,2006-02-14 22:04:36.000,2026-06-04 20:56:50
3,4,2,BARBARA,JONES,BARBARA.JONES@sakilacustomer.org,8,1,2006-02-14 22:04:36.000,2026-06-04 20:56:50
4,5,1,ELIZABETH,BROWN,ELIZABETH.BROWN@sakilacustomer.org,9,1,2006-02-14 22:04:36.000,2026-06-04 20:56:50

## `flm` (1000 rows)

,i01,i02,i03,i04,i05,i06,i07,i08,i09,i10,i11,i12,i13
0,1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,2006,1,None,6,0.99,86,20.99,PG,"Deleted Scenes,Behind the Scenes",2026-06-04 20:56:50
1,2,ACE GOLDFINGER,A Astounding Epistle of a Database Administrat...,2006,1,None,3,4.99,48,12.99,G,"Trailers,Deleted Scenes",2026-06-04 20:56:50
2,3,ADAPTATION HOLES,A Astounding Reflection of a Lumberjack And a ...,2006,1,None,7,2.99,50,18.99,NC-17,"Trailers,Deleted Scenes",2026-06-04 20:56:50
3,4,AFFAIR PREJUDICE,A Fanciful Documentary of a Frisbee And a Lumb...,2006,1,None,5,2.99,117,26.99,G,"Commentaries,Behind the Scenes",2026-06-04 20:56:50
4,5,AFRICAN EGG,A Fast-Paced Documentary of a Pastry Chef And ...,2006,1,None,6,2.99,130,22.99,G,Deleted Scenes,2026-06-04 20:56:50

## `fla` (5462 rows)

   k01  k02                  k03
0    1    1  2026-06-04 20:56:50
1    1   23  2026-06-04 20:56:50
2    1   25  2026-06-04 20:56:50
3    1  106  2026-06-04 20:56:50
4    1  140  2026-06-04 20:56:50

## `flc` (1000 rows)

   l01  l02                  l03
0    1    6  2026-06-04 20:56:50
1    2   11  2026-06-04 20:56:50
2    3    6  2026-06-04 20:56:50
3    4   11  2026-06-04 20:56:50
4    5    8  2026-06-04 20:56:50

## `flt` (0 rows)

Empty DataFrame
Columns: [m01, m02, m03]
Index: []

## `inv` (4581 rows)

   n01  n02  n03                  n04
0    1    1    1  2026-06-04 20:56:50
1    2    1    1  2026-06-04 20:56:50
2    3    1    1  2026-06-04 20:56:50
3    4    1    1  2026-06-04 20:56:50
4    5    1    2  2026-06-04 20:56:50

## `stf` (2 rows)

,o01,o02,o03,o04,o05,o06,o07,o08,o09,o10,o11
0,1,Mike,Hillyer,3,None,Mike.Hillyer@sakilastaff.com,1,1,Mike,8cb2237d0679ca88db6464eac60da96345513964,2026-06-04 20:56:50
1,2,Jon,Stephens,4,None,Jon.Stephens@sakilastaff.com,2,1,Jon,8cb2237d0679ca88db6464eac60da96345513964,2026-06-04 20:56:50

## `sto` (2 rows)

   j01  j02  j03                  j04
0    1    1    1  2026-06-04 20:56:50
1    2    2    2  2026-06-04 20:56:50

## `pay` (16049 rows)

   p01  p02  p03   p04   p05                      p06                  p07
0    1    1    1    76  2.99  2005-05-25 11:30:37.000  2026-06-04 20:56:50
1    2    1    1   573  0.99  2005-05-28 10:35:23.000  2026-06-04 20:56:50
2    3    1    1  1185  5.99  2005-06-15 00:54:12.000  2026-06-04 20:56:50
3    4    1    2  1422  0.99  2005-06-15 18:02:53.000  2026-06-04 20:56:50
4    5    1    2  1476  9.99  2005-06-15 21:08:46.000  2026-06-04 20:56:50

## `ren` (16044 rows)

,q01,q02,q03,q04,q05,q06,q07
0,1,2005-05-24 22:53:30.000,367,130,2005-05-26 22:04:30.000,1,2026-06-04 20:56:50
1,2,2005-05-24 22:54:33.000,1525,459,2005-05-28 19:40:33.000,1,2026-06-04 20:56:50
2,3,2005-05-24 23:03:39.000,1711,408,2005-06-01 22:12:39.000,1,2026-06-04 20:56:50
3,4,2005-05-24 23:04:41.000,2452,333,2005-06-03 01:43:41.000,2,2026-06-04 20:56:50
4,5,2005-05-24 23:05:21.000,2079,222,2005-06-02 04:33:21.000,1,2026-06-04 20:56:50