In [1]:
import pandas as pd
from openai import OpenAI
import os
from src.config import QDRANT_URL, QDRANT_API_KEY, OPENAI_API_KEY, OPENAI_MODEL, OPENAI_API_URL,\
     DENSE_EMBEDDING_MODEL_PATH, OPENAI_MODEL_MINI, INTERIM_DATA_DIR, PROCESSED_DATA_DIR, DEVICE, \
     DEEPSEEK_MODEL
from src.dataset import render_table_ddls, rewrite_query_descriptions_csv, get_sqlite_database_path
from src.script_generator import (
    generate_query_descriptions,
    generate_related_query_descriptions_csv,
    generate_sql_scripts_and_results,
)
from src.vanna_connector import initialize_vanna
from src.search_metrics import run_search_evaluation_pipeline, compute_ranking_metrics
from src.generation_metrics import run_generation_evaluation_pipeline, compute_generation_metrics

/home/user/cursor_projects/vanna-sql/venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
url = os.path.join(PROCESSED_DATA_DIR, "sakila", "sakila_inline_short.sqlite.db")
DATABASE_NAME = "sakila"


sqlite_config = {
    "params": {
        "url": str(url) 
    },
    "type": "sqlite"}

qdrant_config = {"fastembed_model": DENSE_EMBEDDING_MODEL_PATH,
                 "url": QDRANT_URL, 
                 "api_key": QDRANT_API_KEY,
                 "device": DEVICE}

openai_config = {"api_key": OPENAI_API_KEY,
                 "model": OPENAI_MODEL,
                 "base_url": OPENAI_API_URL}

In [3]:
vanna_client = initialize_vanna(db_config=sqlite_config,
                                qdrant_config=qdrant_config,
                                openai_config=openai_config)

Loading weights: 100%|██████████| 391/391 [00:00<00:00, 2426.63it/s]
/home/user/cursor_projects/vanna-sql/venv/lib/python3.10/site-packages/vanna/legacy/qdrant/qdrant.py:49: UserWarning: Api key is used with an insecure connection.
  self._client = QdrantClient(

# Adding DDL to vector store

In [10]:
table_ddls = render_table_ddls(
    database_name=DATABASE_NAME,
    comment_style="inline",
    comment_variant="short",
)

print(table_ddls[0])

CREATE TABLE act ( -- Актёры фильмов.
  a01 numeric NOT NULL, -- Идентификатор актёра.
  a02 VARCHAR(45) NOT NULL, -- Имя актёра.
  a03 VARCHAR(45) NOT NULL, -- Фамилия актёра.
  a04 TIMESTAMP NOT NULL, -- Дата изменения записи.
  PRIMARY KEY (a01)
);

In [ ]:
# # save as example for inference
# df = pd.DataFrame({"ddl": table_ddls})
# df.to_csv(f"{INTERIM_DATA_DIR}/{DATABASE_NAME}/table_ddls_inline_short.csv", index=False)

In [14]:
for table_ddl in table_ddls:
    vanna_client.train(ddl=table_ddl)

Adding ddl: CREATE TABLE act ( -- Актёры фильмов.
  a01 numeric NOT NULL, -- Идентификатор актёра.
  a02 VARCHAR(45) NOT NULL, -- Имя актёра.
  a03 VARCHAR(45) NOT NULL, -- Фамилия актёра.
  a04 TIMESTAMP NOT NULL, -- Дата изменения записи.
  PRIMARY KEY (a01)
);
Adding ddl: CREATE TABLE cnt ( -- Страны.
  c01 SMALLINT NOT NULL, -- Идентификатор страны.
  c02 VARCHAR(50) NOT NULL, -- Название страны.
  c03 TIMESTAMP, -- Дата изменения записи.
  PRIMARY KEY (c01)
);
Adding ddl: CREATE TABLE cty ( -- Города.
  d01 int NOT NULL, -- Идентификатор города.
  d02 VARCHAR(50) NOT NULL, -- Название города.
  d03 SMALLINT NOT NULL, -- Идентификатор страны.
  d04 TIMESTAMP NOT NULL, -- Дата изменения записи.
  PRIMARY KEY (d01),
  CONSTRAINT fk_cty_cnt FOREIGN KEY (d03) REFERENCES cnt (c01) ON DELETE NO ACTION ON UPDATE CASCADE
);
Adding ddl: CREATE TABLE adr ( -- Адреса.
  e01 int NOT NULL, -- Идентификатор адреса.
  e02 VARCHAR(50) NOT NULL, -- Адрес (строка 1).
  e03 VARCHAR(50) DEFAULT NULL, -- Адрес (строка 2).
  e04 VARCHAR(20) NOT NULL, -- Район округ.
  e05 INT NOT NULL, -- Идентификатор города.
  e06 VARCHAR(10) DEFAULT NULL, -- Почтовый индекс.
  e07 VARCHAR(20) NOT NULL, -- Телефон.
  e08 TIMESTAMP NOT NULL, -- Дата изменения записи.
  PRIMARY KEY (e01),
  CONSTRAINT fk_adr_cty FOREIGN KEY (e05) REFERENCES cty (d01) ON DELETE NO ACTION ON UPDATE CASCADE
);
Adding ddl: CREATE TABLE lng ( -- Языки.
  f01 SMALLINT NOT NULL, -- Идентификатор языка.
  f02 CHAR(20) NOT NULL, -- Название языка.
  f03 TIMESTAMP NOT NULL, -- Дата изменения записи.
  PRIMARY KEY (f01)
);
Adding ddl: CREATE TABLE cat ( -- Категории фильмов.
  g01 SMALLINT NOT NULL, -- Идентификатор категории.
  g02 VARCHAR(25) NOT NULL, -- Название категории.
  g03 TIMESTAMP NOT NULL, -- Дата изменения записи.
  PRIMARY KEY (g01)
);
Adding ddl: CREATE TABLE cus ( -- Клиенты проката.
  h01 INT NOT NULL, -- Идентификатор клиента.
  h02 INT NOT NULL, -- Идентификатор магазина.
  h03 VARCHAR(45) NOT NULL, -- Имя клиента.
  h04 VARCHAR(45) NOT NULL, -- Фамилия клиента.
  h05 VARCHAR(50) DEFAULT NULL, -- Email клиента.
  h06 INT NOT NULL, -- Идентификатор адреса.
  h07 CHAR(1) DEFAULT 'Y' NOT NULL, -- Статус активности.
  h08 TIMESTAMP NOT NULL, -- Дата регистрации.
  h09 TIMESTAMP NOT NULL, -- Дата изменения записи.
  PRIMARY KEY (h01),
  CONSTRAINT fk_cus_sto FOREIGN KEY (h02) REFERENCES sto (j01) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT fk_cus_adr FOREIGN KEY (h06) REFERENCES adr (e01) ON DELETE NO ACTION ON UPDATE CASCADE
);
Adding ddl: CREATE TABLE flm ( -- Фильмы.
  i01 int NOT NULL, -- Идентификатор фильма.
  i02 VARCHAR(255) NOT NULL, -- Название фильма.
  i03 BLOB SUB_TYPE TEXT DEFAULT NULL, -- Описание фильма.
  i04 VARCHAR(4) DEFAULT NULL, -- Год выпуска.
  i05 SMALLINT NOT NULL, -- Идентификатор языка.
  i06 SMALLINT DEFAULT NULL, -- Идентификатор оригинала языка.
  i07 SMALLINT DEFAULT 3 NOT NULL, -- Длительность аренды (дни).
  i08 DECIMAL(4,2) DEFAULT 4.99 NOT NULL, -- Стоимость аренды.
  i09 SMALLINT DEFAULT NULL, -- Длительность фильма (минуты).
  i10 DECIMAL(5,2) DEFAULT 19.99 NOT NULL, -- Стоимость замены.
  i11 VARCHAR(10) DEFAULT 'G', -- Рейтинг MPAA.
  i12 VARCHAR(100) DEFAULT NULL, -- Особенности фильма.
  i13 TIMESTAMP NOT NULL, -- Дата изменения записи.
  PRIMARY KEY (i01),
  CONSTRAINT CHECK_flm_i12 CHECK(i12 is null OR i12 LIKE '%Trailers%' OR i12 LIKE '%Commentaries%' OR i12 LIKE '%Deleted Scenes%' OR i12 LIKE '%Behind the Scenes%'),
  CONSTRAINT CHECK_flm_i11 CHECK(i11 IN ('G','PG','PG-13','R','NC-17')),
  CONSTRAINT fk_flm_lng FOREIGN KEY (i05) REFERENCES lng (f01),
  CONSTRAINT fk_flm_lng_original FOREIGN KEY (i06) REFERENCES lng (f01)
);
Adding ddl: CREATE TABLE fla ( -- Связь фильмов и актёров.
  k01 INT NOT NULL, -- Идентификатор актёра.
  k02 INT NOT NULL, -- Идентификатор фильма.
  k03 TIMESTAMP NOT NULL, -- Дата изменения записи.
  PRIMARY KEY (k01, k02),
  CONSTRAINT fk_fla_act FOREIGN KEY (k01) REFERENCES act (a01) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT fk_fla_flm FOREIGN KEY (k02) REFERENCES flm (i01) ON DELETE NO ACTION ON UPDATE CASCADE
);
Adding ddl: CREATE TABLE flc ( -- Связь фильмов и категорий.
  l01 INT NOT NULL, -- Идентификатор фильма.
  l02 SMALLINT NOT NULL, -- Идентификатор категории.
  l03 TIMESTAMP NOT NULL, -- Дата изменения записи.
  PRIMARY KEY (l01, l02),
  CONSTRAINT fk_flc_flm FOREIGN KEY (l01) REFERENCES flm (i01) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT fk_flc_cat FOREIGN KEY (l02) REFERENCES cat (g01) ON DELETE NO ACTION ON UPDATE CASCADE
);
Adding ddl: CREATE TABLE flt ( -- Текстовая таблица для полнотекстового поиска.
  m01 SMALLINT NOT NULL, -- Идентификатор фильма.
  m02 VARCHAR(255) NOT NULL, -- Название фильма.
  m03 BLOB SUB_TYPE TEXT, -- Описание фильма.
  PRIMARY KEY (m01)
);
Adding ddl: CREATE TABLE inv ( -- Инвентарь копии фильмов.
  n01 INT NOT NULL, -- Идентификатор копии.
  n02 INT NOT NULL, -- Идентификатор фильма.
  n03 INT NOT NULL, -- Идентификатор магазина.
  n04 TIMESTAMP NOT NULL, -- Дата изменения записи.
  PRIMARY KEY (n01),
  CONSTRAINT fk_inv_sto FOREIGN KEY (n03) REFERENCES sto (j01) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT fk_inv_flm FOREIGN KEY (n02) REFERENCES flm (i01) ON DELETE NO ACTION ON UPDATE CASCADE
);
Adding ddl: CREATE TABLE stf ( -- Сотрудники проката.
  o01 SMALLINT NOT NULL, -- Идентификатор сотрудника.
  o02 VARCHAR(45) NOT NULL, -- Имя сотрудника.
  o03 VARCHAR(45) NOT NULL, -- Фамилия сотрудника.
  o04 INT NOT NULL, -- Идентификатор адреса.
  o05 BLOB DEFAULT NULL, -- Фотография.
  o06 VARCHAR(50) DEFAULT NULL, -- Email сотрудника.
  o07 INT NOT NULL, -- Идентификатор магазина.
  o08 SMALLINT DEFAULT 1 NOT NULL, -- Статус активности.
  o09 VARCHAR(16) NOT NULL, -- Логин.
  o10 VARCHAR(40) DEFAULT NULL, -- Пароль.
  o11 TIMESTAMP NOT NULL, -- Дата изменения записи.
  PRIMARY KEY (o01),
  CONSTRAINT fk_stf_sto FOREIGN KEY (o07) REFERENCES sto (j01) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT fk_stf_adr FOREIGN KEY (o04) REFERENCES adr (e01) ON DELETE NO ACTION ON UPDATE CASCADE
);
Adding ddl: CREATE TABLE sto ( -- Магазины проката.
  j01 INT NOT NULL, -- Идентификатор магазина.
  j02 SMALLINT NOT NULL, -- Идентификатор менеджера.
  j03 INT NOT NULL, -- Идентификатор адреса.
  j04 TIMESTAMP NOT NULL, -- Дата изменения записи.
  PRIMARY KEY (j01),
  CONSTRAINT fk_sto_stf FOREIGN KEY (j02) REFERENCES stf (o01),
  CONSTRAINT fk_sto_adr FOREIGN KEY (j03) REFERENCES adr (e01)
);
Adding ddl: CREATE TABLE pay ( -- Платежи клиентов.
  p01 int NOT NULL, -- Идентификатор платежа.
  p02 INT NOT NULL, -- Идентификатор клиента.
  p03 SMALLINT NOT NULL, -- Идентификатор сотрудника.
  p04 INT DEFAULT NULL, -- Идентификатор аренды.
  p05 DECIMAL(5,2) NOT NULL, -- Сумма платежа.
  p06 TIMESTAMP NOT NULL, -- Дата платежа.
  p07 TIMESTAMP NOT NULL, -- Дата изменения записи.
  PRIMARY KEY (p01),
  CONSTRAINT fk_pay_ren FOREIGN KEY (p04) REFERENCES ren (q01) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_pay_cus FOREIGN KEY (p02) REFERENCES cus (h01),
  CONSTRAINT fk_pay_stf FOREIGN KEY (p03) REFERENCES stf (o01)
);
Adding ddl: CREATE TABLE ren ( -- Аренда фильмов.
  q01 INT NOT NULL, -- Идентификатор аренды.
  q02 TIMESTAMP NOT NULL, -- Дата выдачи.
  q03 INT NOT NULL, -- Идентификатор копии.
  q04 INT NOT NULL, -- Идентификатор клиента.
  q05 TIMESTAMP DEFAULT NULL, -- Дата возврата.
  q06 SMALLINT NOT NULL, -- Идентификатор сотрудника.
  q07 TIMESTAMP NOT NULL, -- Дата изменения записи.
  PRIMARY KEY (q01),
  CONSTRAINT fk_ren_stf FOREIGN KEY (q06) REFERENCES stf (o01),
  CONSTRAINT fk_ren_inv FOREIGN KEY (q03) REFERENCES inv (n01),
  CONSTRAINT fk_ren_cus FOREIGN KEY (q04) REFERENCES cus (h01)
);

# Generating artificial query description -> SQL queries -> creating descriptions in different format -> adding them to vectore store

In [2]:
openai_client = OpenAI(
    api_key=OPENAI_API_KEY,
    base_url=OPENAI_API_URL,
)

In [ ]:
descriptions_csv_path, schema_description_path, sqlite_db_path = generate_query_descriptions(
    client=openai_client,
    model=OPENAI_MODEL,
    comment_style="inline",
    comment_variant="short",
    database_name=DATABASE_NAME,
    counts_by_difficulty={"easy": 20, "medium": 20, "hard": 20},
    temperature=1.0,
)

print("Descriptions CSV:", descriptions_csv_path)
print("Schema description:", schema_description_path)
print("SQLite DB:", sqlite_db_path)

Descriptions CSV: /home/user/cursor_projects/vanna-sql/data/interim/sakila/query_descriptions_inline_short.csv
Schema description: /home/user/cursor_projects/vanna-sql/data/interim/sakila/schema_description_inline_short.txt
SQLite DB: /home/user/cursor_projects/vanna-sql/data/processed/sakila/sakila_inline_short.sqlite.db

In [16]:
generation_summary = generate_sql_scripts_and_results(
    client=openai_client,
    model=OPENAI_MODEL,
    sqlite_db_path=sqlite_db_path,
    interim_dir=descriptions_csv_path.parent,
    descriptions_csv_path=descriptions_csv_path,
    schema_description_path=schema_description_path,
    temperature=0.2,
)

generation_summary

{'total': 60,
 'generated': 60,
 'saved': 56,
 'failed': 2,
 'empty': 2,
 'invalid_sql': 0}

In [17]:
# descriptions_csv_path = os.path.join(INTERIM_DATA_DIR, "bank_transaction_monitoring", "query_descriptions_inline_short.csv")
# schema_description_path = os.path.join(INTERIM_DATA_DIR, "bank_transaction_monitoring", "schema_description_inline_short.txt")


rewritten_descriptions_csv_path = rewrite_query_descriptions_csv(
    descriptions_csv_path=descriptions_csv_path,
    client=openai_client,
    model=OPENAI_MODEL_MINI,
    schema_description_path=schema_description_path,
    rewrite_styles=("short", "business", "technical"),
    source_column="query",
    temperature=0.9,
)

print("Rewritten descriptions CSV:", rewritten_descriptions_csv_path)

Rewritten descriptions CSV: /home/user/cursor_projects/vanna-sql/data/interim/sakila/query_descriptions_inline_short_rewritten.csv

In [ ]:
# schema_description_path = os.path.join(INTERIM_DATA_DIR, "bank_transaction_monitoring", "schema_description_inline_short.txt")
# rewritten_descriptions_csv_path = os.path.join(INTERIM_DATA_DIR, "bank_transaction_monitoring", "query_descriptions_inline_short_rewritten.csv")

related_descriptions_csv_path = generate_related_query_descriptions_csv(
    rewritten_descriptions_csv_path=rewritten_descriptions_csv_path,
    schema_description_path=schema_description_path,
    client=openai_client,
    model=DEEPSEEK_MODEL,
    rewrite_styles=("short", "business", "technical"),
    source_column="query",
    temperature=0.9,
    num_queries=3,
)

print("Related descriptions CSV:", related_descriptions_csv_path)

Generating related query descriptions: 100%|██████████| 540/540 [2:14:04<00:00, 14.90s/it]

Related descriptions CSV: /home/user/cursor_projects/vanna-sql/data/interim/bank_transaction_monitoring/query_descriptions_inline_short_rewritten_related.csv

In [4]:
DATABASE_NAME = "sakila"
related_descriptions_csv_path = '/home/user/cursor_projects/vanna-sql/data/interim/sakila/query_descriptions_inline_short_rewritten_related.csv'

In [ ]:
search_result_paths = run_search_evaluation_pipeline(
    related_descriptions_csv_path=related_descriptions_csv_path,
    interim_dir=INTERIM_DATA_DIR,
    database_name=DATABASE_NAME,
    qdrant_config=qdrant_config,
    openai_config=openai_config,
    db_config=sqlite_config,
    description_styles=("short", "business", "technical"),
    search_query_columns=None,
    n_results=5,
    comment_style="inline",
    comment_variant="short",
)

print("Search results:", search_result_paths)

Loading weights: 100%|██████████| 391/391 [00:00<00:00, 2710.02it/s]
/home/user/cursor_projects/vanna-sql/venv/lib/python3.10/site-packages/vanna/legacy/qdrant/qdrant.py:49: UserWarning: Api key is used with an insecure connection.
  self._client = QdrantClient(
Uploading DDL (short): 100%|██████████| 16/16 [00:00<00:00, 25.95it/s]
Uploading SQL (short): 100%|██████████| 56/56 [00:01<00:00, 31.83it/s]
Searching (short): 100%|██████████| 504/504 [00:13<00:00, 37.62it/s]
Loading weights: 100%|██████████| 391/391 [00:00<00:00, 2391.43it/s]
/home/user/cursor_projects/vanna-sql/venv/lib/python3.10/site-packages/vanna/legacy/qdrant/qdrant.py:49: UserWarning: Api key is used with an insecure connection.
  self._client = QdrantClient(
Uploading DDL (business): 100%|██████████| 16/16 [00:00<00:00, 22.63it/s]
Uploading SQL (business): 100%|██████████| 56/56 [00:01<00:00, 33.54it/s]
Searching (business): 100%|██████████| 504/504 [00:14<00:00, 35.72it/s]
Loading weights: 100%|██████████| 391/391 [00:00<00:00, 4525.91it/s]
/home/user/cursor_projects/vanna-sql/venv/lib/python3.10/site-packages/vanna/legacy/qdrant/qdrant.py:49: UserWarning: Api key is used with an insecure connection.
  self._client = QdrantClient(
Uploading DDL (technical): 100%|██████████| 16/16 [00:00<00:00, 26.95it/s]
Uploading SQL (technical): 100%|██████████| 56/56 [00:01<00:00, 34.69it/s]
Searching (technical): 100%|██████████| 504/504 [00:14<00:00, 35.81it/s]

Search results: [PosixPath('/home/user/cursor_projects/vanna-sql/data/interim/sakila/search/short_top_5.csv'), PosixPath('/home/user/cursor_projects/vanna-sql/data/interim/sakila/search/business_top_5.csv'), PosixPath('/home/user/cursor_projects/vanna-sql/data/interim/sakila/search/technical_top_5.csv')]
Metrics: [PosixPath('/home/user/cursor_projects/vanna-sql/data/interim/sakila/search/ranking_metrics_short.csv'), PosixPath('/home/user/cursor_projects/vanna-sql/data/interim/sakila/search/ranking_metrics_business.csv'), PosixPath('/home/user/cursor_projects/vanna-sql/data/interim/sakila/search/ranking_metrics_technical.csv')]

In [ ]:
metrics_paths = compute_ranking_metrics(
    search_result_paths=search_result_paths,
    k=5,
)

print("Metrics:", metrics_paths)

In [6]:
for path in metrics_paths:
    print(path.name)
    display(pd.read_csv(path))

ranking_metrics_short.csv

         metric               column  k       value
0           mrr      predicted_short  5    0.535218
1      map_at_k      predicted_short  5    0.535218
2   recall_at_k      predicted_short  5    0.761905
3           mrr   predicted_business  5    0.578571
4      map_at_k   predicted_business  5    0.578571
5   recall_at_k   predicted_business  5    0.773810
6           mrr  predicted_technical  5    0.478175
7      map_at_k  predicted_technical  5    0.478175
8   recall_at_k  predicted_technical  5    0.744048
9           mrr             combined  5    0.562871
10     map_at_k             combined  5    0.535218
11  recall_at_k             combined  5    0.761905
12  num_queries                  all  5  168.000000

ranking_metrics_business.csv

         metric               column  k       value
0           mrr      predicted_short  5    0.516964
1      map_at_k      predicted_short  5    0.516964
2   recall_at_k      predicted_short  5    0.767857
3           mrr   predicted_business  5    0.522421
4      map_at_k   predicted_business  5    0.522421
5   recall_at_k   predicted_business  5    0.773810
6           mrr  predicted_technical  5    0.544940
7      map_at_k  predicted_technical  5    0.544940
8   recall_at_k  predicted_technical  5    0.815476
9           mrr             combined  5    0.546478
10     map_at_k             combined  5    0.516964
11  recall_at_k             combined  5    0.767857
12  num_queries                  all  5  168.000000

ranking_metrics_technical.csv

         metric               column  k       value
0           mrr      predicted_short  5    0.508135
1      map_at_k      predicted_short  5    0.508135
2   recall_at_k      predicted_short  5    0.767857
3           mrr   predicted_business  5    0.544544
4      map_at_k   predicted_business  5    0.544544
5   recall_at_k   predicted_business  5    0.773810
6           mrr  predicted_technical  5    0.498710
7      map_at_k  predicted_technical  5    0.498710
8   recall_at_k  predicted_technical  5    0.785714
9           mrr             combined  5    0.539029
10     map_at_k             combined  5    0.508135
11  recall_at_k             combined  5    0.767857
12  num_queries                  all  5  168.000000

In [ ]:
rewritten_descriptions_csv_path = INTERIM_DATA_DIR / DATABASE_NAME / "query_descriptions_inline_short_rewritten.csv"

predicted_dirs = run_generation_evaluation_pipeline(
    descriptions_csv_path=rewritten_descriptions_csv_path,
    interim_dir=INTERIM_DATA_DIR,
    database_name=DATABASE_NAME,
    models={
        "mini": OPENAI_MODEL_MINI,
        "gpt5": OPENAI_MODEL,
    },
    qdrant_config=qdrant_config,
    openai_config=openai_config,
    comment_styles=("inline", ),
    description_styles=("short", "business",),
    db_config=sqlite_config,
    n_folds=5,
)

print("Predicted result dirs:", predicted_dirs)

In [7]:
ground_truth_results_dir = INTERIM_DATA_DIR / DATABASE_NAME / "results"

generation_metrics_paths = compute_generation_metrics(
    ground_truth_results_dir=ground_truth_results_dir,
    predicted_results_dirs=predicted_dirs,
    descriptions_csv_path=rewritten_descriptions_csv_path,
)

for path in generation_metrics_paths:
    print(path.name)
    df = pd.read_csv(path)
    display(df.groupby("difficulty")['label'].value_counts())

inline_short_mini.csv

difficulty  label
easy        Everything matches                      9
            Not matching values                     9
            Not matching number of columns          2
hard        Not matching number of rows and cols    9
            Not generated                           4
            Not matching number of columns          2
            Not matching number of rows             1
medium      Not matching number of columns          9
            Not matching values                     5
            Not generated                           3
            Everything matches                      2
            Not matching number of rows             1
Name: count, dtype: int64

inline_business_mini.csv

difficulty  label
easy        Everything matches                      11
            Not matching values                      7
            Not matching number of columns           2
hard        Not generated                            8
            Not matching number of rows and cols     7
            Not matching number of columns           1
medium      Not matching number of columns           5
            Not matching values                      5
            Everything matches                       3
            Not generated                            3
            Not matching number of rows              2
            Not matching number of rows and cols     2
Name: count, dtype: int64

inline_short_gpt5.csv

difficulty  label
easy        Everything matches                      11
            Not matching values                      7
            Not matching number of columns           2
hard        Not matching number of rows and cols     6
            Not matching number of columns           4
            Not generated                            3
            Not matching number of rows              3
medium      Not matching values                      9
            Not generated                            4
            Everything matches                       3
            Not matching number of columns           3
            Not matching number of rows and cols     1
Name: count, dtype: int64

inline_business_gpt5.csv

difficulty  label
easy        Everything matches                      14
            Not matching values                      4
            Not matching number of columns           2
hard        Not matching number of rows and cols     8
            Not generated                            6
            Not matching number of columns           2
medium      Not matching number of columns           7
            Not matching values                      6
            Not generated                            3
            Not matching number of rows              2
            Everything matches                       1
            Not matching number of rows and cols     1
Name: count, dtype: int64

In [17]:
df[df["label"] == "Not matching values"]

                                    uuid difficulty                label
1   1f20ef88-9279-4248-9373-dd67f628e895       easy  Not matching values
2   58d71401-2b79-4c01-aa27-d796ade816e6       easy  Not matching values
4   0b31dac1-bbe8-4a24-b1f4-17d4289fcb7c       easy  Not matching values
6   71c28807-ed2e-45ae-92e3-f28bf73e3332       easy  Not matching values
7   5f5b0bf9-0d88-4a6d-b2ff-75c698b26343       easy  Not matching values
11  7dd87e0e-1a56-4abc-855d-dc7f5dc78799       easy  Not matching values
12  c44e6641-c6a1-48ce-9032-2f72be70c8cf       easy  Not matching values
20  3aea5482-5e8a-42be-9898-216a936a48ab     medium  Not matching values
23  605ee2cc-3143-4d32-ba7c-f4ad88b950fd     medium  Not matching values
25  ad40a2da-f48c-4d48-ad2d-c6f833a55201     medium  Not matching values
27  c2c1106d-1c0c-4b61-8e70-6c1a18b4ec61     medium  Not matching values
31  11b5e5d5-552b-4127-88f1-ba0b1e7585cf     medium  Not matching values
33  0aa0168a-a6bd-4adb-82f6-57062b28aa52     medium  Not matching values
37  aa5537b9-f5d0-410f-8cea-0ee9f9ae839d     medium  Not matching values
39  cfe3d5f6-d356-4008-b91f-9b593213f44d     medium  Not matching values
41  a9f0f651-791c-404f-a110-d29ef9cf34dd       hard  Not matching values

In [10]:
url = os.path.join(PROCESSED_DATA_DIR, "sakila", "sakila_inline_short.sqlite.db")
DATABASE_NAME = "sakila"


sqlite_config = {
    "params": {
        "url": str(url) 
    },
    "type": "sqlite"}

qdrant_config = {"fastembed_model": DENSE_EMBEDDING_MODEL_PATH,
                 "url": QDRANT_URL, 
                 "api_key": QDRANT_API_KEY,
                 "device": DEVICE}

openai_config = {"api_key": OPENAI_API_KEY,
                 "model": OPENAI_MODEL_MINI,
                 "base_url": OPENAI_API_URL}

vanna_client = initialize_vanna(db_config=sqlite_config,
                                qdrant_config=qdrant_config,
                                openai_config=openai_config)

Loading weights: 100%|██████████| 391/391 [00:00<00:00, 1927.11it/s]
/home/user/cursor_projects/vanna-sql/venv/lib/python3.10/site-packages/vanna/legacy/qdrant/qdrant.py:49: UserWarning: Api key is used with an insecure connection.
  self._client = QdrantClient(

In [13]:
q = """
Скрипт для выявления клиентов, у которых в любом 7-дневном окне сумма платежей заметно превышает их обычный уровень и средний показатель по стране проживания, с расчетом дневных сумм операций, скользящей 7-дневной суммы, базового среднего или медианы по предыдущим периодам, сравнением с 95-м перцентилем по стране клиента и дополнительной фиксацией случаев, когда в рамках окна платежи проводились через разных сотрудников или в разных магазинах; результат включает клиента, страну, город, период окна, сумму, количество платежей, число сотрудников, число магазинов и ранг подозрительности."
"""
r = vanna_client.generate_sql(question=q)

SQL Prompt: [{'role': 'system', 'content': "You are a SQLite expert. Please help to generate a SQL query to answer the question. Your response should ONLY be based on the given context and follow the response guidelines and format instructions. \n===Tables \nCREATE TABLE pay ( -- Таблица платежей клиентов за аренду. Содержит сумму, дату и связи с rental, customer, staff.\n  p01 int NOT NULL, -- Уникальный идентификатор платежа.\n  p02 INT NOT NULL, -- Идентификатор клиента, совершившего платёж. Внешний ключ к customer.\n  p03 SMALLINT NOT NULL, -- Идентификатор сотрудника, принявшего платёж. Внешний ключ к staff.\n  p04 INT DEFAULT NULL, -- Идентификатор аренды, за которую произведён платёж. Может быть NULL.\n  p05 DECIMAL(5,2) NOT NULL, -- Сумма платежа (до 2 знаков после запятой).\n  p06 TIMESTAMP NOT NULL, -- Дата и время платежа.\n  p07 TIMESTAMP NOT NULL, -- Дата последнего обновления записи платежа. Триггерная.\n  PRIMARY KEY (p01),\n  CONSTRAINT fk_pay_ren FOREIGN KEY (p04) REFERENCES ren (q01) ON DELETE SET NULL ON UPDATE CASCADE,\n  CONSTRAINT fk_pay_cus FOREIGN KEY (p02) REFERENCES cus (h01),\n  CONSTRAINT fk_pay_stf FOREIGN KEY (p03) REFERENCES stf (o01)\n);\n\nCREATE TABLE cus ( -- Таблица клиентов проката. Содержит персональные данные, адрес, статус активности.\n  h01 INT NOT NULL, -- Уникальный идентификатор клиента. Основной ключ для связей с rental и payment.\n  h02 INT NOT NULL, -- Идентификатор магазина, к которому привязан клиент. Внешний ключ к store.\n  h03 VARCHAR(45) NOT NULL, -- Имя клиента. Используется в отчётах и уведомлениях.\n  h04 VARCHAR(45) NOT NULL, -- Фамилия клиента. Участвует в поиске и сортировке.\n  h05 VARCHAR(50) DEFAULT NULL, -- Электронная почта клиента. Используется для коммуникаций.\n  h06 INT NOT NULL, -- Идентификатор адреса клиента. Внешний ключ к address.\n  h07 CHAR(1) DEFAULT 'Y' NOT NULL, -- Статус активности клиента: 'Y' — активен, 'N' — неактивен.\n  h08 TIMESTAMP NOT NULL, -- Дата регистрации клиента. Влияет на историю и лояльность.\n  h09 TIMESTAMP NOT NULL, -- Дата последнего обновления записи клиента. Устанавливается триггерами.\n  PRIMARY KEY (h01),\n  CONSTRAINT fk_cus_sto FOREIGN KEY (h02) REFERENCES sto (j01) ON DELETE NO ACTION ON UPDATE CASCADE,\n  CONSTRAINT fk_cus_adr FOREIGN KEY (h06) REFERENCES adr (e01) ON DELETE NO ACTION ON UPDATE CASCADE\n);\n\nCREATE TABLE cnt ( -- Справочник стран, в которых находятся города и адреса клиентов, магазинов и сотрудников.\n  c01 SMALLINT NOT NULL, -- Уникальный идентификатор страны. Используется для связи с таблицей city.\n  c02 VARCHAR(50) NOT NULL, -- Название страны. Применяется в географических отчётах и адресных формах.\n  c03 TIMESTAMP, -- Дата и время последнего изменения записи о стране. Управляется триггерами.\n  PRIMARY KEY (c01)\n);\n\nCREATE TABLE stf ( -- Таблица сотрудников проката. Содержит личные данные, фото, учётные данные и активность.\n  o01 SMALLINT NOT NULL, -- Уникальный идентификатор сотрудника. Ссылается из rental, payment, store.\n  o02 VARCHAR(45) NOT NULL, -- Имя сотрудника.\n  o03 VARCHAR(45) NOT NULL, -- Фамилия сотрудника.\n  o04 INT NOT NULL, -- Идентификатор адреса сотрудника. Внешний ключ к address.\n  o05 BLOB DEFAULT NULL, -- Фотография сотрудника (BLOB, может быть NULL).\n  o06 VARCHAR(50) DEFAULT NULL, -- Электронная почта сотрудника.\n  o07 INT NOT NULL, -- Идентификатор магазина, в котором работает сотрудник.\n  o08 SMALLINT DEFAULT 1 NOT NULL, -- Статус активности (1 — активен, 0 — неактивен).\n  o09 VARCHAR(16) NOT NULL, -- Логин сотрудника в системе.\n  o10 VARCHAR(40) DEFAULT NULL, -- Пароль (хэшированный или открытый, до 40 символов).\n  o11 TIMESTAMP NOT NULL, -- Дата последнего обновления записи сотрудника.\n  PRIMARY KEY (o01),\n  CONSTRAINT fk_stf_sto FOREIGN KEY (o07) REFERENCES sto (j01) ON DELETE NO ACTION ON UPDATE CASCADE,\n  CONSTRAINT fk_stf_adr FOREIGN KEY (o04) REFERENCES adr (e01) ON DELETE NO ACTION ON UPDATE CASCADE\n);\n\nCREATE TABLE cty ( -- Справочник городов, привязанных к странам. Используется для построения адресов.\n  d01 int NOT NULL, -- Уникальный идентификатор города. Связывается с таблицей address.\n  d02 VARCHAR(50) NOT NULL, -- Название города. Влияет на региональную аналитику продаж.\n  d03 SMALLINT NOT NULL, -- Идентификатор страны, к которой относится город. Внешний ключ к cnt.\n  d04 TIMESTAMP NOT NULL, -- Время последнего обновления записи о городе. Заполняется автоматически.\n  PRIMARY KEY (d01),\n  CONSTRAINT fk_cty_cnt FOREIGN KEY (d03) REFERENCES cnt (c01) ON DELETE NO ACTION ON UPDATE CASCADE\n);\n\nCREATE TABLE ren ( -- Таблица аренды фильмов. Фиксирует дату выдачи, возврата и связь с инвентарём, клиентом, сотрудником.\n  q01 INT NOT NULL, -- Уникальный идентификатор аренды.\n  q02 TIMESTAMP NOT NULL, -- Дата и время выдачи фильма.\n  q03 INT NOT NULL, -- Идентификатор инвентарной копии. Внешний ключ к inventory.\n  q04 INT NOT NULL, -- Идентификатор клиента. Внешний ключ к customer.\n  q05 TIMESTAMP DEFAULT NULL, -- Дата возврата фильма (может быть NULL, если ещё не вернули).\n  q06 SMALLINT NOT NULL, -- Идентификатор сотрудника, оформившего аренду. Внешний ключ к staff.\n  q07 TIMESTAMP NOT NULL, -- Дата последнего обновления аренды. Триггерная.\n  PRIMARY KEY (q01),\n  CONSTRAINT fk_ren_stf FOREIGN KEY (q06) REFERENCES stf (o01),\n  CONSTRAINT fk_ren_inv FOREIGN KEY (q03) REFERENCES inv (n01),\n  CONSTRAINT fk_ren_cus FOREIGN KEY (q04) REFERENCES cus (h01)\n);\n\nCREATE TABLE sto ( -- Таблица магазинов проката. У каждого есть менеджер и адрес.\n  j01 INT NOT NULL, -- Уникальный идентификатор магазина. Связывается с inventory, customer, staff.\n  j02 SMALLINT NOT NULL, -- Идентификатор сотрудника — менеджера магазина. Внешний ключ к staff.\n  j03 INT NOT NULL, -- Идентификатор адреса магазина. Внешний ключ к address.\n  j04 TIMESTAMP NOT NULL, -- Дата последнего обновления магазина.\n  PRIMARY KEY (j01),\n  CONSTRAINT fk_sto_stf FOREIGN KEY (j02) REFERENCES stf (o01),\n  CONSTRAINT fk_sto_adr FOREIGN KEY (j03) REFERENCES adr (e01)\n);\n\nCREATE TABLE lng ( -- Справочник языков, на которых представлены фильмы (например, английский, французский).\n  f01 SMALLINT NOT NULL, -- Уникальный идентификатор языка. Связывается с фильмами в таблице film.\n  f02 CHAR(20) NOT NULL, -- Название языка (до 20 символов). Используется в фильтрации каталога.\n  f03 TIMESTAMP NOT NULL, -- Дата и время последнего обновления записи о языке. Управляется триггерами.\n  PRIMARY KEY (f01)\n);\n\nCREATE TABLE adr ( -- Таблица адресов клиентов, магазинов и сотрудников. Включает улицу, район, телефон и почтовый индекс.\n  e01 int NOT NULL, -- Уникальный идентификатор адреса. Ссылается из таблиц customer, staff, store.\n  e02 VARCHAR(50) NOT NULL, -- Основная строка адреса (улица, дом). Используется в доставке и коммуникациях.\n  e03 VARCHAR(50) DEFAULT NULL, -- Дополнительная строка адреса (корпус, строение). Может быть пустой.\n  e04 VARCHAR(20) NOT NULL, -- Район или округ. Полезен для региональной аналитики.\n  e05 INT NOT NULL, -- Идентификатор города. Внешний ключ к cty.\n  e06 VARCHAR(10) DEFAULT NULL, -- Почтовый индекс. Используется в отчётах и для сверки адресов.\n  e07 VARCHAR(20) NOT NULL, -- Контактный телефон. Необходим для связи с клиентами и сотрудниками.\n  e08 TIMESTAMP NOT NULL, -- Дата последнего изменения адреса. Устанавливается триггерами.\n  PRIMARY KEY (e01),\n  CONSTRAINT fk_adr_cty FOREIGN KEY (e05) REFERENCES cty (d01) ON DELETE NO ACTION ON UPDATE CASCADE\n);\n\nCREATE TABLE fla ( -- Связующая таблица между актёрами и фильмами (many-to-many).\n  k01 INT NOT NULL, -- Идентификатор актёра. Внешний ключ к actor.\n  k02 INT NOT NULL, -- Идентификатор фильма. Внешний ключ к film.\n  k03 TIMESTAMP NOT NULL, -- Дата последнего обновления связи. Триггерная.\n  PRIMARY KEY (k01, k02),\n  CONSTRAINT fk_fla_act FOREIGN KEY (k01) REFERENCES act (a01) ON DELETE NO ACTION ON UPDATE CASCADE,\n  CONSTRAINT fk_fla_flm FOREIGN KEY (k02) REFERENCES flm (i01) ON DELETE NO ACTION ON UPDATE CASCADE\n);\n\n\n===Additional Context \n\nБаза bank_transaction_monitoring описывает клиентов банка, их счета, связи между счетами, операции, уведомления и процентные ставки.\nКлиенты хранятся в btm_cst, где c01 это идентификатор клиента, c02 имя, c04 региональный код клиента.\nОсновные сведения о счетах находятся в btm_accd и btm_accs: номер счета, тип продукта, баланс, статус и роль клиента.\nПоле a06 или s06 показывает роль клиента по счету: P означает основной владелец, S означает вторичная связь.\nОперации по счетам хранятся в btm_trn, где t01 это номер счета, t02 сумма операции, t03 канал, t04 регион, t05 дата.\nПоложительные суммы операций означают поступления, отрицательные суммы означают списания или расходы.\nСвязи между продуктами отражены в btm_rel: r02 это связанный счет, r04 основной или родительский счет.\nТексты уведомлений для клиентов находятся в btm_msg и могут использоваться для задач коммуникации по событиям.\nПроцентные ставки по типам продуктов и периодам находятся в btm_rate.\nДля соединения клиентов со счетами используйте btm_cst.c01 = btm_accd.a01 или btm_cst.c01 = btm_accs.s01; для соединения счетов с операциями используйте btm_accd.a02 = btm_trn.t01 или btm_accs.s02 = btm_trn.t01.\n\n===Response Guidelines \n1. If the provided context is sufficient, please generate a valid SQL query without any explanations for the question. \n2. If the provided context is almost sufficient but requires knowledge of a specific string in a particular column, please generate an intermediate SQL query to find the distinct strings in that column. Prepend the query with a comment saying intermediate_sql \n3. If the provided context is insufficient, please explain why it can't be generated. \n4. Please use the most relevant table(s). \n5. If the question has been asked and answered before, please repeat the answer exactly as it was given before. \n6. Ensure that the output SQL is SQLite-compliant and executable, and free of syntax errors. \n"}, {'role': 'user', 'content': 'Скрипт для выявления клиентов, у которых в любом 7-дневном окне сумма платежей заметно превышает их обычный уровень и средний показатель по стране проживания, с расчетом дневных сумм операций, скользящей 7-дневной суммы, базового среднего или медианы по предыдущим периодам, сравнением с 95-м перцентилем по стране клиента и дополнительной фиксацией случаев, когда в рамках окна платежи проводились через разных сотрудников или в разных магазинах; результат включает клиента, страну, город, период окна, сумму, количество платежей, число сотрудников, число магазинов и ранг подозрительности.'}, {'role': 'assistant', 'content': "WITH\ncustomer_geo AS (\n    SELECT\n        c.h01 AS customer_id,\n        c.h03 || ' ' || c.h04 AS customer_name,\n        city.d02 AS city_name,\n        country.c01 AS country_id,\n        country.c02 AS country_name\n    FROM cus AS c\n    JOIN adr AS a ON a.e01 = c.h06\n    JOIN cty AS city ON city.d01 = a.e05\n    JOIN cnt AS country ON country.c01 = city.d03\n),\npayment_detail AS (\n    SELECT\n        p.p01 AS payment_id,\n        p.p02 AS customer_id,\n        date(p.p06) AS payment_date,\n        CAST(p.p05 AS REAL) AS amount,\n        p.p03 AS staff_id,\n        COALESCE(inv.n03, stf.o07) AS store_id\n    FROM pay AS p\n    JOIN stf AS stf ON stf.o01 = p.p03\n    LEFT JOIN ren AS r ON r.q01 = p.p04\n    LEFT JOIN inv AS inv ON inv.n01 = r.q03\n),\ndaily_payments AS (\n    SELECT\n        customer_id,\n        payment_date,\n        SUM(amount) AS daily_amount,\n        COUNT(*) AS daily_payment_count\n    FROM payment_detail\n    GROUP BY customer_id, payment_date\n),\nwindow_7d_amounts AS (\n    SELECT\n        d.customer_id,\n        date(d.payment_date, '-6 days') AS window_start,\n        d.payment_date AS window_end,\n        SUM(dp.daily_amount) AS window_amount,\n        SUM(dp.daily_payment_count) AS payment_count\n    FROM daily_payments AS d\n    JOIN daily_payments AS dp\n        ON dp.customer_id = d.customer_id\n       AND dp.payment_date BETWEEN date(d.payment_date, '-6 days') AND d.payment_date\n    GROUP BY\n        d.customer_id,\n        date(d.payment_date, '-6 days'),\n        d.payment_date\n),\nwindow_7d_staff_store AS (\n    SELECT\n        d.customer_id,\n        date(d.payment_date, '-6 days') AS window_start,\n        d.payment_date AS window_end,\n        COUNT(DISTINCT p.staff_id) AS staff_count,\n        COUNT(DISTINCT p.store_id) AS store_count\n    FROM daily_payments AS d\n    JOIN payment_detail AS p\n        ON p.customer_id = d.customer_id\n       AND p.payment_date BETWEEN date(d.payment_date, '-6 days') AND d.payment_date\n    GROUP BY\n        d.customer_id,\n        date(d.payment_date, '-6 days'),\n        d.payment_date\n),\nwindow_7d AS (\n    SELECT\n        a.customer_id,\n        a.window_start,\n        a.window_end,\n        a.window_amount,\n        a.payment_count,\n        s.staff_count,\n        s.store_count\n    FROM window_7d_amounts AS a\n    JOIN window_7d_staff_store AS s\n        ON s.customer_id = a.customer_id\n       AND s.window_start = a.window_start\n       AND s.window_end = a.window_end\n),\ncustomer_baseline AS (\n    SELECT\n        w.*,\n        AVG(w.window_amount) OVER (\n            PARTITION BY w.customer_id\n            ORDER BY w.window_end\n            ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING\n        ) AS customer_prev_avg_7d,\n        COUNT(*) OVER (\n            PARTITION BY w.customer_id\n            ORDER BY w.window_end\n            ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING\n        ) AS previous_window_count\n    FROM window_7d AS w\n),\ncountry_windows AS (\n    SELECT\n        cb.*,\n        cg.customer_name,\n        cg.city_name,\n        cg.country_id,\n        cg.country_name\n    FROM customer_baseline AS cb\n    JOIN customer_geo AS cg ON cg.customer_id = cb.customer_id\n),\ncountry_distribution AS (\n    SELECT\n        country_id,\n        window_amount,\n        CUME_DIST() OVER (\n            PARTITION BY country_id\n            ORDER BY window_amount\n        ) AS country_cume_dist\n    FROM country_windows\n),\ncountry_p95 AS (\n    SELECT\n        country_id,\n        MIN(window_amount) AS country_p95_7d\n    FROM country_distribution\n    WHERE country_cume_dist >= 0.95\n    GROUP BY country_id\n),\nscored AS (\n    SELECT\n        cw.customer_id,\n        cw.customer_name,\n        cw.country_name,\n        cw.city_name,\n        cw.window_start,\n        cw.window_end,\n        cw.window_amount,\n        cw.payment_count,\n        cw.staff_count,\n        cw.store_count,\n        cw.customer_prev_avg_7d,\n        cp.country_p95_7d,\n        (cw.window_amount / NULLIF(cw.customer_prev_avg_7d, 0))\n        + (cw.window_amount / NULLIF(cp.country_p95_7d, 0))\n        + CASE WHEN cw.staff_count > 1 THEN 0.5 ELSE 0 END\n        + CASE WHEN cw.store_count > 1 THEN 0.5 ELSE 0 END AS suspicion_score\n    FROM country_windows AS cw\n    JOIN country_p95 AS cp ON cp.country_id = cw.country_id\n    WHERE cw.previous_window_count >= 3\n      AND cw.customer_prev_avg_7d > 0\n      AND cw.window_amount >= 2.0 * cw.customer_prev_avg_7d\n      AND cw.window_amount >= cp.country_p95_7d\n)\nSELECT\n    customer_id,\n    customer_name,\n    country_name,\n    city_name,\n    window_start,\n    window_end,\n    ROUND(window_amount, 2) AS window_amount,\n    payment_count,\n    staff_count,\n    store_count,\n    ROUND(customer_prev_avg_7d, 2) AS customer_previous_avg_7d,\n    ROUND(country_p95_7d, 2) AS country_p95_7d,\n    RANK() OVER (\n        ORDER BY suspicion_score DESC, window_amount DESC, payment_count DESC\n    ) AS suspicion_rank\nFROM scored\nORDER BY suspicion_rank, customer_id, window_end;"}, {'role': 'user', 'content': 'Скрипт для выявления клиентов с аномальной платежной активностью по месяцам: анализируются любые 7 последовательных дней, в которых сумма платежей и число операций превышают собственные средние значения клиента за предыдущие 30 дней минимум в 3 раза, при условии что платежи в таком окне проводились более чем одним сотрудником или через более чем один магазин; по каждому месяцу формируется список таких клиентов с указанием города и страны, суммарных и количественных показателей подозрительного окна, средних 30-дневных значений, числа задействованных сотрудников и магазинов, а также ранга клиента внутри месяца по величине превышения над историческим средним.'}, {'role': 'assistant', 'content': "WITH RECURSIVE\nbounds AS (\n  SELECT\n    date(MIN(p06), '-30 day') AS min_date,\n    date(MAX(p06)) AS max_date\n  FROM pay\n),\ncalendar(dt) AS (\n  SELECT min_date\n  FROM bounds\n  UNION ALL\n  SELECT date(dt, '+1 day')\n  FROM calendar\n  CROSS JOIN bounds\n  WHERE dt < max_date\n),\ncustomer_bounds AS (\n  SELECT\n    p02 AS customer_id,\n    date(MIN(p06)) AS min_date,\n    date(MAX(p06)) AS max_date\n  FROM pay\n  GROUP BY p02\n),\nwindow_starts AS (\n  SELECT\n    cb.customer_id,\n    c.dt AS window_start\n  FROM customer_bounds cb\n  JOIN calendar c\n    ON c.dt BETWEEN cb.min_date AND cb.max_date\n),\nraw_payments AS (\n  SELECT\n    p.p01 AS payment_id,\n    p.p02 AS customer_id,\n    p.p03 AS staff_id,\n    s.o07 AS store_id,\n    date(p.p06) AS payment_date,\n    p.p05 AS amount\n  FROM pay p\n  JOIN stf s\n    ON s.o01 = p.p03\n),\nwindow_metrics AS (\n  SELECT\n    ws.customer_id,\n    ws.window_start,\n    date(ws.window_start, '+6 day') AS window_end,\n    COALESCE(SUM(\n      CASE\n        WHEN rp.payment_date >= ws.window_start\n         AND rp.payment_date < date(ws.window_start, '+7 day')\n        THEN rp.amount\n        ELSE 0\n      END\n    ), 0) AS window_payment_sum,\n    COUNT(\n      CASE\n        WHEN rp.payment_date >= ws.window_start\n         AND rp.payment_date < date(ws.window_start, '+7 day')\n        THEN rp.payment_id\n      END\n    ) AS window_payment_count,\n    COUNT(DISTINCT\n      CASE\n        WHEN rp.payment_date >= ws.window_start\n         AND rp.payment_date < date(ws.window_start, '+7 day')\n        THEN rp.staff_id\n      END\n    ) AS staff_count,\n    COUNT(DISTINCT\n      CASE\n        WHEN rp.payment_date >= ws.window_start\n         AND rp.payment_date < date(ws.window_start, '+7 day')\n        THEN rp.store_id\n      END\n    ) AS store_count,\n    COALESCE(SUM(\n      CASE\n        WHEN rp.payment_date >= date(ws.window_start, '-30 day')\n         AND rp.payment_date < ws.window_start\n        THEN rp.amount\n        ELSE 0\n      END\n    ), 0) * 7.0 / 30.0 AS avg_30d_payment_sum,\n    COUNT(\n      CASE\n        WHEN rp.payment_date >= date(ws.window_start, '-30 day')\n         AND rp.payment_date < ws.window_start\n        THEN rp.payment_id\n      END\n    ) * 7.0 / 30.0 AS avg_30d_payment_count\n  FROM window_starts ws\n  LEFT JOIN raw_payments rp\n    ON rp.customer_id = ws.customer_id\n   AND rp.payment_date >= date(ws.window_start, '-30 day')\n   AND rp.payment_date < date(ws.window_start, '+7 day')\n  GROUP BY\n    ws.customer_id,\n    ws.window_start\n),\nsuspicious_windows AS (\n  SELECT\n    strftime('%Y-%m', wm.window_start) AS month,\n    wm.customer_id,\n    wm.window_start,\n    wm.window_end,\n    wm.window_payment_sum,\n    wm.window_payment_count,\n    wm.avg_30d_payment_sum,\n    wm.avg_30d_payment_count,\n    wm.staff_count,\n    wm.store_count,\n    wm.window_payment_sum / wm.avg_30d_payment_sum AS amount_exceedance_ratio,\n    wm.window_payment_count / wm.avg_30d_payment_count AS count_exceedance_ratio\n  FROM window_metrics wm\n  WHERE wm.avg_30d_payment_sum > 0\n    AND wm.avg_30d_payment_count > 0\n    AND wm.window_payment_sum >= 3.0 * wm.avg_30d_payment_sum\n    AND wm.window_payment_count >= 3.0 * wm.avg_30d_payment_count\n    AND (wm.staff_count > 1 OR wm.store_count > 1)\n),\nbest_customer_month_window AS (\n  SELECT *\n  FROM (\n    SELECT\n      sw.*,\n      ROW_NUMBER() OVER (\n        PARTITION BY sw.month, sw.customer_id\n        ORDER BY\n          sw.am

In [14]:
vanna_client.run_sql(r)

,customer_id,customer_name,country_name,city_name,window_start,window_end,window_amount,payment_count,staff_count,store_count,customer_previous_avg_7d,country_p95_7d,suspicion_rank
0,181,ANA BRADLEY,United States,Memphis,2005-07-26,2005-08-01,82.86,14,2,2,18.97,41.91,1
1,459,TOMMY COLLAZO,Iran,Qomsheh,2005-07-26,2005-08-01,96.84,16,2,2,23.38,44.92,2
2,425,FRANCIS SIKES,Mexico,San Juan Bautista Tuxtepec,2005-07-02,2005-07-08,41.93,7,2,2,7.99,40.91,3
3,331,ERIC ROBERT,Argentina,Santa F,2005-07-01,2005-07-07,40.94,6,2,2,7.98,37.91,4
4,2,PATRICIA JOHNSON,United States,San Bernardino,2005-07-24,2005-07-30,62.89,11,2,2,13.37,41.91,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
570,573,BYRON BOX,Kazakstan,Zhezqazghan,2005-07-27,2005-08-02,34.92,8,2,2,17.17,34.92,571
571,517,BRAD MCCURDY,Taiwan,Chungho,2005-07-06,2005-07-12,41.90,10,2,2,20.62,41.90,572
572,332,STEPHEN QUALLS,Bangladesh,Dhaka,2005-07-27,2005-08-02,62.87,13,2,2,31.05,62.87,573
573,498,GENE SANBORN,Oman,Salala,2005-07-26,2005-08-01,31.92,8,2,2,15.85,31.92,574
574,307,JOSEPH JOY,Brazil,Angra dos Reis,2005-07-27,2005-08-02,42.91,9,1,2,18.90,40.93,575

In [15]:
script = """WITH customer_geo AS (
    SELECT
        c.h01 AS customer_id,
        c.h03 || ' ' || c.h04 AS customer_name,
        co.c02 AS country_name,
        ci.d02 AS city_name
    FROM cus AS c
    JOIN adr AS a ON a.e01 = c.h06
    JOIN cty AS ci ON ci.d01 = a.e05
    JOIN cnt AS co ON co.c01 = ci.d03
),
daily_payments AS (
    SELECT
        p.p02 AS customer_id,
        date(p.p06) AS payment_day,
        SUM(CAST(p.p05 AS REAL)) AS daily_amount,
        COUNT(*) AS daily_payment_count,
        COUNT(DISTINCT p.p03) AS daily_staff_count,
        COUNT(DISTINCT stf.o07) AS daily_store_count
    FROM pay AS p
    JOIN stf AS stf ON stf.o01 = p.p03
    GROUP BY
        p.p02,
        date(p.p06)
),
daily_base AS (
    SELECT
        dp.*,
        AVG(dp.daily_amount) OVER (
            PARTITION BY dp.customer_id
            ORDER BY julianday(dp.payment_day)
            ROWS BETWEEN 30 PRECEDING AND 1 PRECEDING
        ) AS prev_avg_30d,
        MEDIAN(dp.daily_amount) OVER (
            PARTITION BY dp.customer_id
            ORDER BY julianday(dp.payment_day)
            ROWS BETWEEN 30 PRECEDING AND 1 PRECEDING
        ) AS prev_median_30d
    FROM daily_payments AS dp
),
windows AS (
    SELECT
        d1.customer_id,
        d1.payment_day AS window_start,
        date(d1.payment_day, '+6 day') AS window_end,
        SUM(d2.daily_amount) AS window_sum,
        SUM(d2.daily_payment_count) AS window_payment_count,
        SUM(d2.daily_staff_count) AS window_staff_count_raw,
        SUM(d2.daily_store_count) AS window_store_count_raw,
        MAX(d2.prev_avg_30d) AS base_avg_30d,
        MAX(d2.prev_median_30d) AS base_median_30d
    FROM daily_base AS d1
    JOIN daily_base AS d2
      ON d2.customer_id = d1.customer_id
     AND d2.payment_day >= d1.payment_day
     AND d2.payment_day < date(d1.payment_day, '+7 day')
    GROUP BY
        d1.customer_id,
        d1.payment_day
),
country_p95 AS (
    SELECT
        cg.country_name,
        dp.payment_day,
        percentile_cont(0.95) WITHIN GROUP (ORDER BY dp.daily_amount) AS country_p95_amount
    FROM daily_payments AS dp
    JOIN customer_geo AS cg
      ON cg.customer_id = dp.customer_id
    GROUP BY
        cg.country_name,
        dp.payment_day
),
suspicious AS (
    SELECT
        w.customer_id,
        cg.customer_name,
        cg.country_name,
        cg.city_name,
        w.window_start,
        w.window_end,
        w.window_sum,
        w.window_payment_count,
        w.window_staff_count_raw AS staff_count,
        w.window_store_count_raw AS store_count,
        COALESCE(w.base_avg_30d, w.base_median_30d) AS baseline_value,
        cp.country_p95_amount,
        CASE
            WHEN COALESCE(w.base_avg_30d, w.base_median_30d) IS NULL OR COALESCE(w.base_avg_30d, w.base_median_30d) = 0 THEN NULL
            ELSE w.window_sum / COALESCE(w.base_avg_30d, w.base_median_30d)
        END AS suspicion_ratio,
        ROW_NUMBER() OVER (
            PARTITION BY cg.country_name
            ORDER BY
                (w.window_sum / NULLIF(COALESCE(w.base_avg_30d, w.base_median_30d), 0)) DESC,
                w.window_sum DESC
        ) AS suspicion_rank
    FROM windows AS w
    JOIN customer_geo AS cg
      ON cg.customer_id = w.customer_id
    LEFT JOIN country_p95 AS cp
      ON cp.country_name = cg.country_name
     AND cp.payment_day BETWEEN w.window_start AND w.window_end
    WHERE w.window_sum > COALESCE(w.base_avg_30d, w.base_median_30d) * 2
      AND w.window_sum > COALESCE(cp.country_p95_amount, 0)
      AND (w.window_staff_count_raw > 1 OR w.window_store_count_raw > 1)
)
SELECT
    customer_id,
    customer_name,
    country_name,
    city_name,
    window_start,
    window_end,
    ROUND(window_sum, 2) AS window_sum,
    window_payment_count,
    staff_count,
    store_count,
    ROUND(baseline_value, 2) AS baseline_value,
    ROUND(country_p95_amount, 2) AS country_p95_amount,
    ROUND(suspicion_ratio, 2) AS suspicion_ratio,
    suspicion_rank
FROM suspicious
ORDER BY suspicion_rank, window_sum DESC;"""

In [16]:
vanna_client.run_sql(script)

DatabaseError: Execution failed on sql 'WITH customer_geo AS (
    SELECT
        c.h01 AS customer_id,
        c.h03 || ' ' || c.h04 AS customer_name,
        co.c02 AS country_name,
        ci.d02 AS city_name
    FROM cus AS c
    JOIN adr AS a ON a.e01 = c.h06
    JOIN cty AS ci ON ci.d01 = a.e05
    JOIN cnt AS co ON co.c01 = ci.d03
),
daily_payments AS (
    SELECT
        p.p02 AS customer_id,
        date(p.p06) AS payment_day,
        SUM(CAST(p.p05 AS REAL)) AS daily_amount,
        COUNT(*) AS daily_payment_count,
        COUNT(DISTINCT p.p03) AS daily_staff_count,
        COUNT(DISTINCT stf.o07) AS daily_store_count
    FROM pay AS p
    JOIN stf AS stf ON stf.o01 = p.p03
    GROUP BY
        p.p02,
        date(p.p06)
),
daily_base AS (
    SELECT
        dp.*,
        AVG(dp.daily_amount) OVER (
            PARTITION BY dp.customer_id
            ORDER BY julianday(dp.payment_day)
            ROWS BETWEEN 30 PRECEDING AND 1 PRECEDING
        ) AS prev_avg_30d,
        MEDIAN(dp.daily_amount) OVER (
            PARTITION BY dp.customer_id
            ORDER BY julianday(dp.payment_day)
            ROWS BETWEEN 30 PRECEDING AND 1 PRECEDING
        ) AS prev_median_30d
    FROM daily_payments AS dp
),
windows AS (
    SELECT
        d1.customer_id,
        d1.payment_day AS window_start,
        date(d1.payment_day, '+6 day') AS window_end,
        SUM(d2.daily_amount) AS window_sum,
        SUM(d2.daily_payment_count) AS window_payment_count,
        SUM(d2.daily_staff_count) AS window_staff_count_raw,
        SUM(d2.daily_store_count) AS window_store_count_raw,
        MAX(d2.prev_avg_30d) AS base_avg_30d,
        MAX(d2.prev_median_30d) AS base_median_30d
    FROM daily_base AS d1
    JOIN daily_base AS d2
      ON d2.customer_id = d1.customer_id
     AND d2.payment_day >= d1.payment_day
     AND d2.payment_day < date(d1.payment_day, '+7 day')
    GROUP BY
        d1.customer_id,
        d1.payment_day
),
country_p95 AS (
    SELECT
        cg.country_name,
        dp.payment_day,
        percentile_cont(0.95) WITHIN GROUP (ORDER BY dp.daily_amount) AS country_p95_amount
    FROM daily_payments AS dp
    JOIN customer_geo AS cg
      ON cg.customer_id = dp.customer_id
    GROUP BY
        cg.country_name,
        dp.payment_day
),
suspicious AS (
    SELECT
        w.customer_id,
        cg.customer_name,
        cg.country_name,
        cg.city_name,
        w.window_start,
        w.window_end,
        w.window_sum,
        w.window_payment_count,
        w.window_staff_count_raw AS staff_count,
        w.window_store_count_raw AS store_count,
        COALESCE(w.base_avg_30d, w.base_median_30d) AS baseline_value,
        cp.country_p95_amount,
        CASE
            WHEN COALESCE(w.base_avg_30d, w.base_median_30d) IS NULL OR COALESCE(w.base_avg_30d, w.base_median_30d) = 0 THEN NULL
            ELSE w.window_sum / COALESCE(w.base_avg_30d, w.base_median_30d)
        END AS suspicion_ratio,
        ROW_NUMBER() OVER (
            PARTITION BY cg.country_name
            ORDER BY
                (w.window_sum / NULLIF(COALESCE(w.base_avg_30d, w.base_median_30d), 0)) DESC,
                w.window_sum DESC
        ) AS suspicion_rank
    FROM windows AS w
    JOIN customer_geo AS cg
      ON cg.customer_id = w.customer_id
    LEFT JOIN country_p95 AS cp
      ON cp.country_name = cg.country_name
     AND cp.payment_day BETWEEN w.window_start AND w.window_end
    WHERE w.window_sum > COALESCE(w.base_avg_30d, w.base_median_30d) * 2
      AND w.window_sum > COALESCE(cp.country_p95_amount, 0)
      AND (w.window_staff_count_raw > 1 OR w.window_store_count_raw > 1)
)
SELECT
    customer_id,
    customer_name,
    country_name,
    city_name,
    window_start,
    window_end,
    ROUND(window_sum, 2) AS window_sum,
    window_payment_count,
    staff_count,
    store_count,
    ROUND(baseline_value, 2) AS baseline_value,
    ROUND(country_p95_amount, 2) AS country_p95_amount,
    ROUND(suspicion_ratio, 2) AS suspicion_ratio,
    suspicion_rank
FROM suspicious
ORDER BY suspicion_rank, window_sum DESC;': near "(": syntax error